- name: Install Python Packages.
  apt:
    name:
      - make
      - build-essential
      - libssl1.0-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - git
    state: present

- name: Install pyenv
  shell: curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

- name: Install python 3.4 with pyenv
  become_user: nms
  shell: pyenv install 3.4.8